### ISSUE TITLE
Error checking for GMonth, GYearMonth, GDay, GMonthDay

### ISSUE THREAD

**Issue by kevinchristianson** [Colectica/cogs#125]
Use built-in calendar class (Julian Calendar or Gregorian Calendar) to verify that properties for GMonth, GDay, GYearMonth and GMonthDay are valid.

**Comment by kevinchristianson** [comment]
@DanSmith Is this something worth working on? It's simple to do but I'm wondering whether we want to limit the valid inputs for these simple types

**Comment by DanSmith** [comment]
- [ ] Convert the fields to public properties
- [ ] Add broadest data annotations (not calendar validated)
- [ ] Expand property names (M becomes Month, D becomes Day, you can use visual studio's rightclick->rename to change all uses pretty easily)
- [ ] Rename parameter names to match json names (zone -> timezone)
- [ ] Rename Value to Day/Year/etc
