### ISSUE TITLE
Correction to Cogs CsPublisher

### ISSUE THREAD

**Issue by clementpeihengtan** [Colectica/cogs#69]
@kevinchristianson

**Comment by clementpeihengtan** [comment]
1) Use toJson method instead of calling the object directly
```Csharp
            JProperty json = new JProperty(ID, new JObject(
                new JProperty("ID", ID),
                new JProperty("Name", Name),
                new JProperty("LingualDescription", 
                    new JArray(
                        from item in LingualDescription
                        select new JObject(
                            new JProperty("MultilingualString", item)))), //make it tojson as this is an object, not a string
                new JProperty("CountryOfOrigin", CountryOfOrigin),
                new JProperty("Date", Date),
                new JProperty("Duration", Duration)));
```
2) Reusable type ToJson Method is not being called, instead the super class method ToJson is being called
3) Modify dimension's toJson() method. 
```Csharp
public JObject ToJson()
        {
            JArray heights = new JArray();
            foreach(var item in Height)
            {
                heights.Add(item);
            }
            JObject json = new JObject() {
                new JProperty("Width", Width),
                new JProperty("Length", Length),
                new JProperty("Height", heights)};
            return json;
        }
```
Should look something like this when it is serialized
```Json
"Size": {
        "Width": 12,
        "Length": 13,
        "Height": [14,15]
      }
```

**Comment by kevinchristianson** [comment]
When reading Json, reusable types do not have their properties set

**Comment by kevinchristianson** [comment]
Tests to make sure we check:
all simple types
simple types as lists
reusable types
reusable types as lists
reusable types that have item types as properties

**Comment by kevinchristianson** [comment]
Things not fully implemented:
Parsing CogsDate
Parsing a list of a simple type

**Comment by kevinchristianson** [comment]
@clementpeihengtan @DanSmith 
Currently the Json schema requires that a hamburger have a patty. If that is what we want, then how should we go about testing a hamburger's DateTime property?

**Comment by DanSmith** [comment]
We can add a property to another type which doesn't have required fields.
For example, add a new property with a DateTime datatype to Condiment called ManufactureTime

**Comment by kevinchristianson** [comment]
@clementpeihengtan There is one test that fails: a list of CogsTypes with a duration gives an error when Validated by the Json schema. Maybe I created the list or duration improperly but both look well-formed to me. Would you mind taking a look at it?
#95

**Comment by kevinchristianson** [comment]
@clementpeihengtan After adding a few more tests I found that I am getting a similar issue for lists of DateTimes, if you'd be willing to take a look at that as well. I'll create a pull request soon so you can see the test that is failing.

**Comment by clementpeihengtan** [comment]
Sure, I'll look into it., once the pull request is merged
